glitchdotcom/shared-components

lib/icon.js, lib/index.js, lib/loader.js, lib/stories.js, lib/story-utils.js, lib/themes.js
http://neat-sea-1.glitch.me/
- @ehmorris: Is this correctly proportioned to its surrounding text? We rarely use loaders inline on community. Also, any thoughts on what to do in the 'prefer-reduced-motion` case?
=> Neat sea 1: Loader

lib/avatar.js, lib/icon.js, lib/index.js, lib/stories.js, lib/story-utils.js, lib/text-input.js
http://veil-can.glitch.me/#StoryAvatar
This component does fairly little -- its essentially just an image with a fallback src and some presets for borders. However, its a useful building block for more domain-specific components. For example, community uses a component like this to build `<ProfileList>`, which takes an array of users and renders an overlapping stack of avatars which link to each user's profile and show tooltips showing each user's name.
=> Veil can: Avatar component

changelog.md, lib/checkbox-button.js, lib/index.js, lib/stories.js
http://boulder-insect.glitch.me/#StoryCheckboxButton
=> Boulder insect: checkbox button component

changelog.md, lib/animation-container.js, lib/index.js, lib/stories.js
http://endurable-fan.glitch.me/#StoryAnimationContainer
I think the docs might be confusing for this section.
=> Endurable fan: AnimationContainer component

lib/index.js, lib/mark.js, lib/stories.js, lib/system.js, lib/theme-preview.js, lib/themes.js
Basic docs: http://nervous-cattle.glitch.me/
RootStyle and LocalStyle: http://nervous-cattle.glitch.me/#Story_RootStyle_and_LocalStyle
Themes: http://nervous-cattle.glitch.me/#StoryThemes
@sheridanvk is this more clear?
=> Nervous cattle: update documentation for themes

changelog.md, lib/animation-container.js, lib/index.js, lib/keyboard-navigation.js, lib/results-list.js, lib/search-results.js, lib/stories.js
ResultsList: http://jet-accelerator.glitch.me/#StoryResultsList
SearchResults: http://jet-accelerator.glitch.me/#StorySearchResults
- is the keyboard navigation correct?
- is it clear how one is supposed to use the SearchResults component?
=> Jet accelerator: search results

lib/themes.js, package.json
http://numerous-smartphone.glitch.me/#StoryThemes
=> Numerous smartphone: improve contrast ratio for placeholder text

changelog.md, lib/button-group.js, lib/button.js, lib/index.js, lib/keyboard-navigation.js, lib/stories.js, package-lock.json, package.json
http://aromatic-brass.glitch.me/#StoryButtonGroup_and_ButtonSegment
=> Aromatic brass: ButtonGroup & SegmentedButton

changelog.md, lib/button.js, package-lock.json, package.json
=> Fallacious garment: disabled button styling

changelog.md, package-lock.json, package.json, shrinkwrap.yaml
This fixes a server side rendering bug caused by the client code and the server importing different copies of styled-components
=> Move styled-components into a peer dependency

changelog.md, lib/text-input.js, package-lock.json, package.json
=> Luxurious navy: add 3px border radius to opaque text inputs

CONTRIBUTING.md
Documenting the processing Allyson and I went through to try to update the NPM package.
=> Toothsome table: Adding Contributing.md file

lib/text-input.js
Already updated in shared-components.glitch.me; getting github in sync
=> Add semicolon to fix font size

changelog.md, package-lock.json, package.json
This is what's on live, I followed the steps outlined in contributing.md but found that I couldn't push from there because I have 2fa enabled.
I think we might want to edit our docs to have all of the update steps done locally and then at the end you just have to git pull on the glitch app
=> Shared components

lib/notification.js
Merged it into another branch by accident!
=> Merge previously approved PR into master

changelog.md, lib/icon.js, package-lock.json, package.json
=> Boosted icon

lib/avatar.js
Needed for the project avatars in the new header's new project pop. 
https://bottlenose-glowing-thimbleberry.glitch.me/#StoryAvatar
=> Add square variant for avatar

lib/themes.js
Notifications are showing up behind the ShareProjectOverlay right now; this PR switches them.
=> Swap notification and overlay z-index

.autorc, package.json
- Add .autorc file
- Add `author` field to package.json
<details>
<summary>📦 Published PR as canary version: <code>0.18.13-canary.128.4410929.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.18.13-canary.128.4410929.0
yarn add @glitchdotcom/shared-components@0.18.13-canary.128.4410929.0
```
</details>
=> add author details

lib/icon.js
SSIA!
<details>
<summary>📦 Published PR as canary version: <code>0.22.1--canary.139.65b6981.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.22.1--canary.139.65b6981.0
yarn add @glitchdotcom/shared-components@0.22.1--canary.139.65b6981.0
```
</details>
=> fix protocol on twemoji urls

lib/icon.js, package-lock.json, package.json, rollup.config.js
<details>
<summary>📦 Published PR as canary version: <code>0.22.5--canary.153.508a423.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.22.5--canary.153.508a423.0
yarn add @glitchdotcom/shared-components@0.22.5--canary.153.508a423.0
```
</details>
=> Update twomoji links

server/changelog.js
<details>
<summary>📦 Published PR as canary version: <code>0.22.5--canary.154.eb41429.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.22.5--canary.154.eb41429.0
yarn add @glitchdotcom/shared-components@0.22.5--canary.154.eb41429.0
```
</details>
=> fix github actions
