changelog.md, lib/animation-container.js, package.json
http://scythe-print.glitch.me/#StoryAnimationContainer
- add `reducedMotionAnimation` prop to AnimationContainer for alternate animations if prefers-reduced-motion is enabled
@clottman I'd like the docs to include a link to guidelines on what kind of animations are suitable for reduced motion uses, do you have suggestions?
=> Scythe print: handle reduced motion in animation container

lib/icon.js
Icon sizes are always inline, unless directly overridden
=> Shrouded march: remove icon size docs

changelog.md, lib/button.js, lib/popover.js, package-lock.json, package.json
I think this is what we want even for popovers: 
`white-space: normal`
`white-space: nowrap`
=> Change button whitespace to normal

lib/themes.js
Used of lighter active button background color for lightTheme to prevent high contrast switching when clicking buttons.
active button color for lightTheme:
active button color for darkTheme:
Preview changes at https://mulberry-tuck.glitch.me/
=> Updated active button background colors

lib/button.js, lib/stories.js, lib/story-utils.js
I created navigation to make it easier to go through the Shared Components documentation.
I tried to only include the primary components (for example, `Avatar` appears in the nav, but not `Avatar sizes` or `Avatar variants`). 
The nav hides for smaller screens (<1200px)
Testable at https://gorgeous-persimmon.glitch.me
=> Gorgeous persimmon - Added nav

changelog.md, lib/block.js, lib/popover.js, package-lock.json, package.json
Some popovers in the community site need the ability to be open on page load, so this adds that functionality
=> Blossom bougon: add startOpen prop to popover

changelog.md, lib/popover.js, package-lock.json, package.json
Currently when you open a popover and click anywhere else, your focus returns back to the popover button that opened it. This was done purposely to ensure users do not lose focus when they press escape. But it looks like we've accidentally created other focus bugs by accident. Now if you click to open a popover and then click on any other interactive element your focus does not go to that interactive element but back to the old popover to show you closed it. This means if you're clicking around between popovers or between input fields it's pretty easy to get confused. Here's a screen recording illustrating what I'm talking about: https://recordit.co/0e7KhdW4Mf
My first thought was to remove this functionality entirely, but I realized when you tab _into_ a popover and then press escape you …
=> Popover fix

CONTRIBUTING.md, README.md, lib/icon.js
New instructions for adding Emoji to `shared-components` are in `Contributing.md`
Also added the coffin emoji for Delete Account purposes.
https://plump-chime.glitch.me/
=> Added Emoji Instructions & Coffin Emoji

CONTRIBUTING.md, lib/overlay.js, lib/themes.js
adds a z-index to overlays (already did this with popovers)
=> 🍋🚊 Checkpoint

lib/block.js, lib/overlay.js, lib/popover.js, lib/stories.js
Two changes here: 
1. The navigation was set at a sticky position far down in the window, so if you had the developer tools open in the browser while looking at the page, you couldn't access the bottom of the navigation section. I fixed this by making the navigation sticky to the top of the window, and only as tall as the viewport (scrolling otherwise). 
Old 
New 
2. Add links in the Popover and Overlay section to point to the 'Blocks for Popover and Overlay Components' documentation.
=> Rich-red: make navigation usable when dev tools is open, and add links to popover/overlay blocks

lib/button-group.js, lib/button.js, lib/results-list.js
Adds a stylized focus ring around buttons and row items, and makes the hover, focus, and active styles consistent between those elements.
Examples:
=> Add a consistent focus state to buttons and rowItems

lib/results-list.js, lib/stories.js
Adds back dividers between result items in a results list and takes an optional private prop that will give it a yellow background.
remix: https://peppered-deltadromeus.glitch.me/#StoryResultsList
=> Peppered deltadromeus: ResultItem fixes

lib/block.js, lib/popover.js, watch.json
Should prevent very wide pop-overs such as 
Also removed extraneous padding on popover titles.
=> Sparkly dichondra: Set Max-Width on Pop-overs

CONTRIBUTING.md
This PR is mainly to publish changes to the pop-over max-width, which I tested in a release candidate at https://low-nebula.glitch.me/@community
I also updated the README with instructions on how to create and test a release candidate.
=> Sparkly-Dichondra: added release candidate instructions

changelog.md, lib/block.js, lib/button.js, lib/popover.js, package-lock.json, package.json
updates to styling: they were already being globally overwritten on the community site, so I figured I might as well add them here instead.
@FogCreek/design see any reason not to go for this?
@sarahzinger I can test out your new documentation/flow with this release!
=> Ajar math: a couple of styling updates

CONTRIBUTING.md, README.md, sh/publish.sh
This still needs to be fully QA'd but I think this is an improvement? I was more hopeful that we'd have better ways to test a WIP version of shared-components in community, but this invalid hooks error was kind of a pain. Feel free to share feedback, I'm sure this isn't 💯 and I'm probably missing easier ways to do things/explain things/etc.  
Also I'd like to confirm my changes to the publish script. In my mind this makes sense but I also don't want to test it by publishing unnecessary versions if I can help it, so please check my logic at least :)
=> Some publish script changes and updated contributing documentation

lib/button.js, package.json, shrinkwrap.yaml
[Clubhouse ticket](https://app.clubhouse.io/glitch/story/6187/css-in-latest-shared-components-button-is-broken-true-rendering-next-to-font-size-property)
I can't reproduce this bug in the examples at shared-components.glitch.me, but here's what some buttons in the community site look like sometimes: 
Note the CSS, on the line under `border`. And that the button is smaller than normal (hard to tell in the screenshot)
I tested this by using `createRemoteComponent` in a local branch.
=> Ritzy-dichondra: fix extraneous "true" in CSS for Button

lib/notification.js
Per issue here, we want to add some more padding and make the width of notifications more flexible. Screenshots of the changes are in that issue.
https://app.clubhouse.io/glitch/story/8589/change-default-padding-for-notifications#activity-8614
=> Improve padding and width for Notifications

lib/notification.js
This PR puts `removeNotification` into context so it can be used inside the NotificationProvider, and modifies the `createNotification` function to return the notification (which includes its ID), such that the id can then later be used to remove the notification.
Demo here:
https://glitch.com/edit/#!/equatorial-mushroom-a3p4w27vxl?path=lib/notification.js:1:0
I added a button "Remove Last Notification" into the Notification Story to demonstrate how to remove the last notification that was added.
=> Add ability to remove notifications

lib/notification.js
In general, the notifications that we show up disappear after 2.5s. This makes that the default, and adds a persistent state in the cases where we don't want them to disappear.
Worth noting that in the Community site, there's an inline Notification that is usually persistent. I think we should handle this case by creating a separate InlineNotification component which is used outside of NotificationsProvider, that sets the Notification to persistent.
=> Added persistent state for notifications and made default timeout 2.5s

CONTRIBUTING.md, README.md, lib/stories.js, package-lock.json, test/remote-component/index.js, test/remote-component/server.js
=> @fogcreek replaced with @glitchdotcom

lib/results-list.js
Makes the code example for ResultsList match the code used in the rendered ResultsList. (see line 232 of `lib/results-list.js`)
=> ResultsList: make code sample match how the component actually works

CONTRIBUTING.md, package.json
Updated testing-shared-components-locally-in-another-project instructions. Inspired by [slack conversation](https://fogcreek.slack.com/archives/CJ1G77E87/p1583449968001600?thread_ts=1583447625.001000&cid=CJ1G77E87)
=> Update instructions for testing locally & creating prerelease versions

lib/icon.js
https://bottlenose-glowing-thimbleberry.glitch.me/#StoryIcon 
No change to the component contract: `<Icon icon="external" />` will do the same thing, but will respond to color changes the way the other SVG icons do.
=> Make external icon into an svg so it can go dark-mode 

server/rollup.js, watch.json
- Fix the file watcher for the dev environment so that the bundle rebuilds when files change
- Update watch.json to let the file watcher rebuild instead of restarting on changes
- no changes to bundle code, so no version bump
=> fix file watcher

sh/update.sh
- must always run `./sh/update.sh branch_and_remix_name`
- can run `./sh/update.sh branch_and_remix_name`
- can also just run `./sh/update.sh`, and the branch/remix used will be the current working branch from git. 
1. I'm on branch resisted-prickly-sand, I want to update from glitch.com/~resisted-prickly-sand and the branch resisted-prickly-sand on github
2. I'm on branch `test`, I want to update from glitch.com/~rich-red and to the branch rich-red on github.
=> Update update script be smarter

.circleci/config.yml, package.json
Also do a build as part of `test`. Circle CI will automatically (with no config file defined, so by default) run `npm run test` so we can just jam more stuff we want to test in there for now, until it becomes necessary to have a real Circle CI config of our own.
=> Circle CI changes 

changelog.md, lib/avatar.js, package-lock.json, package.json
Previously, `<Avatar src={null} defaultSrc={fallbackImg} />` would flicker with the fallback image, and then go blank. I believe this is because:
- if an img src is a string, it will try to load the URL at that string and error if it fails; however, if src is nullish then it just shows nothing
- useEffect runs after mount, not just after updates, so the useEffect handler immediately overwrites the initial value of activeSrc
- the previous version of the useEffect handler did not have defaultSrc as a fallback value if src was falsy, so it was setting activeSrc to src's nullish value
With this PR, `<Avatar src={null} defaultSrc={fallbackImg} />` shows the fallback image consistently. I also added a story that demonstrates the defaultSrc behavior and verifies that the provided change works …
=> fix defaultSrc behavior if src is null

changelog.md, lib/editable-project-domain.js, package-lock.json, package.json
EditableProjectDomain shared component does not "sync" -- i.e. when the domain in the header nav EditableProjectDomain changes, the domain on the page does not update, and vice versa. This PR fixes this behavior.
=> Update domain when initial name changes

changelog.md, lib/toggle.js, package-lock.json, package.json
https://app.clubhouse.io/glitch/story/16429/update-toggle-shared-component-for-app-dashboard-usage
- add `disabled` state
- make labels configurable (and blank by default)
- document how to override colors
=> update toggle component to work with app dashboard

lib/icon.js
Adds a text-color version of the lightning bolt icon. The [mockups](https://www.figma.com/file/rtQwLELjwY75LVljdBouz1/052720_UptimeLimits_MI?node-id=590%3A489) for the app dashboard show a cyan-colored lightning bolt icon in the static app badge:
Since the existing one cannot be recolored, I figured adding a full-vector version was best.
I don't have an npm account linked to the org, so help with deploying this after merging would be appreciated. Thank you!
=> [ch16918] Add text-colored lightning bolt icon.

lib/visually-hidden.js
The Uptime Limits UI changes include showing buttons on the app dashboard on hover, replacing the date column contents. For accessibility we want the per-row buttons to always be available to screen readers as well.
React doesn't make it easy to _sometimes_ wrap an element with another element (you have to have an extra variable containing either the wrapper or React.Fragment based on a variable). Adding a prop that can control whether the styles are actually applied or not seemed like a better solution.
=> Add `show` prop to VisuallyHidden.

lib/block.js, lib/overlay.js
This PR adds a banner variant for Overlay. The goal is to create an Overlay option that looks close to the one in this design spec: https://www.figma.com/file/LLBMwcB37R4fQrn7kgZKUi/061820_PrivateApps_MI%2BKAC?node-id=34%3A0
This introduces new variants in `block.js` for this Overlay banner, specifically. I commented above the relevant banners to hopefully make this clearer. 
How to Test
1. Go to `overlay.js`
2. Add `variant={'banner'}` to the `Overlay`, `Title,` and `Info` components
3. Add `variant={'alignright'}` to the `Actions` component
4. When you open an overlay, it should look like the overlay in the attached screenshot: 
5. Test in dark mode!
=> add banner variant to Overlay

lib/icon.js, lib/tooltip.js
This has two commits needed for the uptime limits UI work:
- Adds clock and info icons.
- Fixes a bug with multiline text in `TooltipContainer`: When the box is taller than one line of text and the arrow is on the bottom, the arrow moves up into the box and overlays the text. The fix is to position the arrow using `bottom` instead of `top` so that it is height-independent.
=> Add clock/info icons and fix multiline-tooltip bug.

lib/results-list.js, lib/search-results.js
This is causing a blank box to appear under the search box when you click into it; this PR fixes it.
Before:
After:
See Search Results in `obtainable-excessive-salary.glitch.me` for a demo.
=> Don't show the Results List if there's nothing to show yet

lib/notification.js
Currently, a click on the close button of a notification propagates through the DOM, resulting in things like overlays closing. This PR addresses that issue.
=> Don't propagate notification close button clicks

lib/tooltip.js
This is a very very small change to prevent the `InvisibleHoverTarget` within `TooltipContainer` from covering up the elements below it.
@glitchdotcom/product-eng 
[19522](https://app.clubhouse.io/glitch/stories/space/17257/p1-private-project-blockers)
=> fix tooltip

lib/results-list.js
I updated some of the styling for the `SearchResults` component to match the Figma for the new private project overlay: https://www.figma.com/file/LLBMwcB37R4fQrn7kgZKUi/061820_PrivateProjects_MI%2BKAC?node-id=585%3A643
Some things to note/outstanding questions:
- In the Figma, the text on hover and focus is white. I chatted with @iuloshi and she suggested making it black for accessibility reasons, and that's what's reflected in this PR.
- Will we run into issues with the padding when we put user avatars next to the result item names and description?
- The result item description text looks like it's a little bigger than the result item name, but I copied over the font-size and line height from the Figma. Let me know if I should adjust accordingly or leave as is.
Original search results …
=> Update Styling to SearchResults component

.github/workflows/release.yml, package-lock.json, package.json
Instead of pinning these, allow higher versions as we phase out of the community codebase
<details>
<summary>📦 Published PR as canary version: <code>0.21.0--canary.137.1e6d245.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.21.0--canary.137.1e6d245.0
yarn add @glitchdotcom/shared-components@0.21.0--canary.137.1e6d245.0
```
</details>
=> Allow a higher version of React & Node

lib/system.js
<details>
<summary>📦 Published PR as canary version: <code>0.22.0--canary.138.56f33e7.0</code></summary>
<br />
```bash
npm install @glitchdotcom/shared-components@0.22.0--canary.138.56f33e7.0
yarn add @glitchdotcom/shared-components@0.22.0--canary.138.56f33e7.0
```
</details>
=> No longer specify the font-family in LocalStyle

lib/popover.js, lib/tooltip.js, package-lock.json, package.json
Since the recent upgrade to a newer version of `styled-components` we've been seeing the error (labeled a warning, but counted as an error in the developer tools) below on all page loads, due to the tooltip component's `fallback` prop.
<details>
<summary><code>Warning: Received `false` for a non-boolean attribute `fallback`.</code></summary>
```
Warning: Received `false` for a non-boolean attribute \`fallback\`.
If you want to write it to the DOM, pass a string instead: fallback="false" or fallback={value.toString()}.
If you used to conditionally omit it with fallback={condition && value}, pass fallback={condition ? value : undefined} instead.
```
</details>
The problem is that when we pass the `fallback` attribute to the `styled.div`, it's giving that attribute to the `div` itself, which …
=> Use transient prop to avoid passing `fallback` to underlying div
